spring:
  datasource:
    url: jdbc:mysql://localhost:3306/business?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root1234

dubbo:
  application:
    name: forum-user
  protocol:
    name: dubbo
    port: 20001
  registry:
    address: nacos://127.0.0.1:8848
